image:
  file: .gitpod/Dockerfile
  context: .gitpod

ports:
  - port: 8888
    onOpen: ignore

tasks:
  - name: Jupyter
    command: |
      conda activate pycon2019
      jupyter notebook --ip='0.0.0.0' --NotebookApp.token='' --NotebookApp.password=''
