name: pycon2019
channels:
  - conda-forge
dependencies:
  - python
  - aiohttp
  - trio
  - pip
  - cookiecutter
  - notebook
  - pandas
  - nodejs
  - jupyterlab
  - bqplot
  - pythreejs
  - line_profiler
  - matplotlib
  - rpy2
  - simplegeneric
  - cython
  - pillow
  - ipyleaflet
  - ipympl
  - jupyter